basic_app/urls.py
from django.urls import path
from basic_app import views

#TEMPLATE URLS!

app_name = 'basic_app'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login')
]

learning_users/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls')),
    path('', views.logout, name='logout'),
    path('', views.special, name='special')

]

basic_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # additional
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

basic_app/views.py
from django.shortcuts import render
from basic_app.form import UserForm, UserProfileInfoForm


from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required



# Create your views here.
def index(request):
    return render(request, 'basic_app/index.html')

@login_required
def special(request):
    return HttpResponse('You are logged in Nice!')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'basic_app/register.html', {'user_form': user_form,
                                                       'profile_form': profile_form,
                                                       'registered': registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('ACCOUNT NOT ACTIVE')
        else:
            print("Someone tried to login and failed")
    else:
        print("The rest isn't a post")

templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="navbar-nav">
            <a class="navbar-brand" href="{% url 'index' %}">DJANGO</a>
            <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
            <a class="nav-item nav-link" href="{% url 'basic_app:register' %}">Registration</a>

        </div>
    </nav>

    <div>
        {% block body_block %}
        {% endblock %}
    </div>

</body>
</html>

templates/basic_app/index.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% block body_block %}
    <div class="jumbotron">
        <h1>Django level five!</h1>
    </div>
{%  endblock %}

templates/basic_app/login.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% block body_block %}
    <div class="jumbotron">
        <h1>Please Login</h1>
        <form action="{% url 'basic_app:user_login' %}" method="post"></form>
            {% csrf_token %}
            <label for="username">Username</label>
            <input type="text" name="username" placeholder="Enter Username">

            <label for="password">Password</label>
            <input type="password" name="password">

            <input type="submit" name="" value="Login">

    </div>
{% endblock %}

templates/basic_app/register.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% block body_block %}
    <div class="jumbotron">
        {% if registered %}
            <H1>Thank you for registering!</H1>
        {% else %}
            <h1>Register here!</h1>
            <h3>Fill out the form:</h3>

            <form class="" action="index.html" enctype="multipart/form-data"  method="POST">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <input  type="submit" name="" value="Register">
            </form>
        {% endif %}

    </div>
{% endblock %}

templates/basic_app/register/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="navbar-nav">
            <a class="navbar-brand" href="{% url 'index' %}">DJANGO</a>
            <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
            <a class="nav-item nav-link" href="{% url 'basic_app:register' %}">Registration</a>

            {% if user.is_autehticated%}
                <a class="navbar-link" href="{% url 'logout' %}">Logout</a>
            {% else %}
                <a class="navbar-link" href="{% url 'basic_app:user_login' %}">Login</a>
            {% endif %}

        </div>
    </nav>

    <div>
        {% block body_block %}
        {% endblock %}
    </div>

</body>
</html>

templates/basic_app/register/index.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% block body_block %}
    <div class="jumbotron">
        <h1>Django level five!</h1>
    </div>
{%  endblock %}